Initial migration to poetry
cds-snc/notification-document-download-api pull request #104
Opened 2023-01-26 19:18 UTC by whabanks

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2023-02-01 19:34 UTC, jzbahrai approved these changes

2023-02-06 17:57 UTC, sastels requested changes
We might be missing something. Or I'm dockering wrong!

I did
```
$ docker build -f ci/Dockerfile -t dd-api-test .
```
and then got an error about gunicorn when running the image.
```
$ docker run dd-api-test
sh: gunicorn: not found
```

Building the image currently on `main` works / runs.

2023-02-07 16:10 UTC, whabanks commented
> We might be missing something. Or I'm dockering wrong!
> 
> I did
> 
> ```
> $ docker build -f ci/Dockerfile -t dd-api-test .
> ```
> 
> and then got an error about gunicorn when running the image.
> 
> ```
> $ docker run dd-api-test
> sh: gunicorn: not found
> ```
> 
> Building the image currently on `main` works / runs.

You are Dockering correctly! I pushed a change to prevent Poetry from creating a virtual environment to install dependencies into, thus "hiding" them from the system Python installation.

2023-02-07 16:48 UTC, sastels approved these changes
I added one little change - adding "poetry run" to the line for "make test". Also
- ran in the devcontainer 
- built ci/Dockerfile and ran that. 
- looking into the docker container to verify that we're not using virtual envs in staging / prod

Let's get this to staging!

2023-02-07 16:54 UTC, merged