upgrade python to 3.12
cds-snc/notification-document-download-api pull request #200
Opened 2024-11-14 16:13 UTC by sastels

# Summary | Résumé

Upgrade python.

## Related Issues | Cartes liées

* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-document-download-api/195
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/355

# Test instructions | Instructions pour tester la modification

rebuild and run document-download-api locally together with `main` api.

# Release Instructions | Instructions pour le déploiement

None.

# Reviewer checklist | Liste de vérification du réviseur

- [ ] This PR does not break existing functionality.
- [ ] This PR does not violate GCNotify's privacy policies.
- [ ] This PR does not raise new security concerns. Refer to our GC Notify Risk Register document on our Google drive.
- [ ] This PR does not significantly alter performance.
- [ ] Additional required documentation resulting of these changes is covered (such as the README, setup instructions, a related ADR or the technical documentation).

> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.

2024-11-14 16:14 UTC, sastels commented on pyproject.toml
> -notifications-utils = { git = "https://github.com/cds-snc/notifier-utils.git", tag = "52.2.7"}
Change this after the utils PR merges

2024-11-14 16:15 UTC, sastels commented on pyproject.toml
> +notifications-utils = { git = "https://github.com/cds-snc/notifier-utils.git", branch = "python-3.12"}
Change this after the utils PR merges

2024-12-04 16:03 UTC, sastels commented on Makefile
> +
Just added to help test gunicorn locally

2024-12-04 16:24 UTC, ben851 requested changes
Can we use the sha on the docker image to remain consistent/secure

2024-12-04 16:24 UTC, ben851 commented on ci/Dockerfile
> +FROM python:3.12-alpine3.20
Can we use the sha here as well?

2024-12-04 18:02 UTC, ben851 commented on ci/Dockerfile
> +FROM python:3.12-alpine3.20
that I did not know!

2024-12-04 18:02 UTC, ben851 approved these changes
LGTM

2024-12-04 19:05 UTC, merged